### PR TITLE
Restructuring Repository

### PR DESCRIPTION
**Pull request by lgabriel-oracle**
Now that the service provides a Terraform stack for prerequisites, the code here will no longer be the latest version.

Additionally, this repository is now needed to provide scripting examples that support migration activities.

A few ideas:
- Have a repository that customer can easily clone in CloudShell
- Lab related setup scripts
- Scripts for migrations and troubleshooting
- Allow multiple contributors with simple management of README.md.

### CODE REVIEW

**Comment by ansokolo-oracle** [comment]
Let's make it happen!

**Review by ansokolo-oracle — APPROVED** [review]
Let's make it happen!

**Comment by lgabriel-oracle** [comment]
Clone into CloudShell so a deep hierarchy is not preferred.

**Comment by ansokolo-oracle** [comment]
Approved

**Review by ansokolo-oracle — APPROVED** [review]
Approve

**Comment by lgabriel-oracle** [comment]
Done.

**Pull request merged**
